#!/usr/bin/env sh

if [ "init" == "$1" ]; then
  shift
  ./scripts/init.sh $@
  exit "$?"
fi

scenario="$1"
scenario_cmd=""
for s in $(./scripts/scenarios.sh); do
  if [ "$s" == "$scenario" ]; then
    scenario_cmd="-var-file=scenarios/$s.tfvars"
    shift
    break
  fi
done

make scenario="$scenario_cmd" 0="$0 <scenario>" "$@"
