## template: jinja
#cloud-config
packages_update: true
packages_upgrade: true

packages:
  - ca-certificates
  - sysstat

ssh_pwauth: false

# create the docker group (for the mastodon instances)
groups:
  - docker

# Add default auto created user to docker group
system_info:
  default_user:
    groups: [docker]

users:
  - name: ansible
    gecos: Ansible User
    groups: users,adm,wheel,docker
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: true
    ssh_authorized_keys:
      - ${ansibleSshKey}

# https://ubuntu.com/server/docs/security-trust-store
write_files:
  - path: /usr/local/share/ca-certificates/minica.crt
    encoding: base64
    content: ${base64encode(minicaRoot)}

runcmd:
  - [ update-ca-certificates ]

merge_how:
  - name: list
    settings: [append]
  - name: dict
    settings: [no_replace, recurse_list]

final_message: |
  -----------------
  version: $version
  timestamp: $timestamp
  datasource: $datasource
  uptime: $uptime
  cloud-init has finished
