---
- name: Clean monitoring logs
  hosts: all
  tasks:
    - name: Vacuum journal - clean monitoring logs
      become: yes
      shell: "journalctl --rotate --vacuum-time=1s"
    - name: Delete remote user credentials
      file:
        state: absent
        path: users/

- name: Clean instance files
  hosts: instances
  tasks:
    - name: Remove mastodon containers
      command:
        chdir: /home/ansible
        cmd: bash -c "hostname=$(hostname) docker compose --project-name mastodon rm --volumes --force"
    - name: Delete Postgres Database
      become: yes
      file:
        state: absent
        path: /home/ansible/mastodon/postgres14
    - name: Delete Redis Database
      become: yes
      file:
        state: absent
        path: /home/ansible/mastodon/redis
    - name: Delete local user credentials
      file:
        state: absent
        path: users.txt
    - name: Delete admin credentials
      file:
        state: absent
        path: admin.txt

- name: Clean client files
  hosts: clients
  tasks:
    - name: Delete Tootbench client log
      file:
        state: absent
        path: tootbench.log.gz

- name: Clean local files
  hosts: localhost
  tasks:
    - name: Delete user credential files
      file:
        path: users/
        state: absent
