---
- hosts: localhost
  gather_facts: true
  tasks:
    - name: Get current timestamp
      set_fact:
        timestamp: >-
          {{ ansible_date_time.year }}-{{
          ansible_date_time.month }}-{{ ansible_date_time.day }}T{{
          ansible_date_time.hour }}:{{ ansible_date_time.minute }}:{{
          ansible_date_time.second }}
        run_once: true
        cachable: yes

- name: Write monitoring logs
  hosts: instances
  tasks:
    - name: Create log folder
      shell: "mkdir -p logs/{{ hostvars['localhost']['timestamp'] }}/{{ inventory_hostname }}/"
    - name: Write vmstat service monitoring log
      shell: "journalctl -u vmstat -o short-unix | gzip > logs/{{ hostvars['localhost']['timestamp'] }}/{{ inventory_hostname }}/vmstat.log.gz"
    - name: Write iostat cpu service monitoring log
      shell: "journalctl -u iostat-cpu -o short-unix | gzip > logs/{{ hostvars['localhost']['timestamp'] }}/{{ inventory_hostname }}/iostat-cpu.log.gz"
    - name: Write iostat disk service monitoring log
      shell: "journalctl -u iostat-disk -o short-unix | gzip > logs/{{ hostvars['localhost']['timestamp'] }}/{{ inventory_hostname }}/iostat-disk.log.gz"
    - name: Write mpstat service monitoring log
      shell: "journalctl -u mpstat -o short-unix | gzip > logs/{{ hostvars['localhost']['timestamp'] }}/{{ inventory_hostname }}/mpstat.log.gz"
    - name: Write docker stats service monitoring log
      shell: "journalctl -u docker-stats -o short-unix | gzip > logs/{{ hostvars['localhost']['timestamp'] }}/{{ inventory_hostname }}/docker-stats.log.gz"
    - name: Collect logs
      synchronize:
        mode: pull
        src: logs/
        dest: logs/

- name: Collect Tootbench Benchmark log
  hosts: clients
  tasks:
    - name: Collect tootbench client log
      fetch:
        src: tootbench.log.gz
        dest: logs/{{ hostvars['localhost']['timestamp'] }}/
