---
- name: Install monitoring services
  hosts: all
  become: yes
  tasks:
    - name: Upgrade system packages
      apt:
        upgrade: yes
        update_cache: yes
    # (continuos) vmstat --unit M --one-header --timestamp 5
    - name: Install vmstat service
      copy:
        src: vmstat.service
        dest: /etc/systemd/system/
    # iostat -c 5
    - name: Install iostat-cpu service
      copy:
        src: iostat-cpu.service
        dest: /etc/systemd/system/
    # iostat -mdN sda 5
    - name: Install iostat-disk service
      copy:
        src: iostat-disk.service
        dest: /etc/systemd/system/
    # mpstat -P ALL 5
    - name: Install mpstat service
      copy:
        src: mpstat.service
        dest: /etc/systemd/system/
    # docker stats (as the it took to long with a timer and --no-stream)
    - name: Install docker-stats service
      copy:
        src: docker-stats.service
        dest: /etc/systemd/system/
    - name: Install ping service
      copy:
        src: ping@.service
        dest: /etc/systemd/system/

- name: Setup Mastodon on the instances
  hosts: instances
  tasks:
    - name: Docker compose yaml
      copy:
        src: docker-compose.yml
        dest: .
    - name: .env.production
      template:
        src: .env.production.jinja2
        dest: .env.production
    - name: Create cert directory
      shell: "mkdir -p cert/{{ hostname }}/"
      args:
        creates: cert/{{ hostname }}/
    - name: Install minica certificate
      copy:
        src: cert/{{ hostname }}/cert.pem
        local_follow: true
        dest: cert/{{ hostname }}/cert.pem
    - name: Install minica private key
      copy:
        src: cert/{{ hostname }}/key.pem
        local_follow: true
        dest: cert/{{ hostname }}/key.pem

    - name: Pull images
      command: docker compose --project-name mastodon pull --quiet
      environment:
        MASTODON_VERSION: "{{ mastodon_version }}"
    - name: Pre-compile Mastodon assets
      command:
        cmd: docker compose --project-name mastodon run --rm precompile-assets
      environment:
        hostname: "{{ hostname }}"
        MASTODON_VERSION: "{{ mastodon_version }}"
    - name: Migrate Mastodon database
      command:
        cmd: docker compose --project-name mastodon run --rm db-migrate
      environment:
        hostname: "{{ hostname }}"
        MASTODON_VERSION: "{{ mastodon_version }}"
      args:
        creates: mastodon/postgres14
    - name: Add util scripts
      copy:
        src: scripts/
        dest: .
        local_follow: true
        mode: preserve
    - name: Create Mastodon admin user
      command:
        cmd: sh createAdminUser.sh
      args:
        creates: admin.txt
    - name: Create Mastodon users
      shell:
        cmd: "docker compose --project-name mastodon run --rm --name {{ hostname }} -v $(pwd)/createUser.sh:/createUser.sh --entrypoint=/createUser.sh tootctl {{ users }} user {{ hostname }} > users.txt"
      environment:
        MASTODON_VERSION: "{{ mastodon_version }}"
      args:
        creates: users.txt
    - name: Collect user credentials
      fetch:
        src: users.txt
        dest: users/
    - name: Distribute user credentials
      copy:
        src: users
        dest: ./

- name: Setup clients
  hosts: clients
  tasks:
    - name: Distribute app dependencies
      copy:
        src: lib
        dest: app/
        local_follow: true
    - name: Distribute app
      copy:
        src: client.jar
        dest: app/client.jar
        local_follow: true
    - name: Distribute user credentials
      copy:
        src: users
        dest: ./
      # todo: if multiple clients, then split files by number of clients

- name: Setup tootbench
  hosts: clients
  become: yes
  tasks:
    - name: Install app service
      copy:
        src: tootbench.service
        dest: /etc/systemd/system/
