---
- name: Setup and run Mastodon on the instances
  hosts: instance
  tasks:
    # todo monitoring
    # todo add users based on config
    - name: Start mastodon containers
      command:
        chdir: /home/ansible
        cmd: bash -c "hostname=$(hostname) docker compose --project-name mastodon up --wait"

    - name: Collect user credentials
      fetch:
        src: users.txt
        dest: users/
    # collect user files

- name: Setup clients
  hosts: client
  tasks:

    - name: Distribute app dependencies
      copy:
        src: lib
        dest: app/
        local_follow: true

    - name: Distribute app
      copy:
        src: client.jar
        dest: app/client.jar
        local_follow: true

    - name: Distribute user credentials
      copy:
        src: users
        dest: ./
      # todo: if multiple clients, then split files by number of clients

    # todo start client (and thus Benchmark)
    # todo wait for specified time OR setup a systemd timer on the client stopping the client and sending a ntfy
    # todo stop clients & benchmark
