---
- name: Start monitoring
  hosts: instances
  become: yes
  tasks:
    - name: Start vmstat monitoring service
      systemd:
        name: vmstat.service
        state: started
    - name: Start iostat cpu monitoring service
      systemd:
        name: iostat-cpu.service
        state: started
    - name: Start iostat disk monitoring service
      systemd:
        name: iostat-disk.service
        state: started
    - name: Start mpstat monitoring service
      systemd:
        name: mpstat.service
        state: started
    - name: Start docker stats monitoring service
      systemd:
        name: docker-stats.service
        state: started
    - name: Start docker stats monitoring service timer
      systemd:
        name: docker-stats.timer
        state: started

- name: Start Mastodon
  hosts: instances
  tasks:
    - name: Start mastodon containers
      command:
        chdir: /home/ansible
        cmd: docker compose --project-name mastodon up --wait
      environment:
        hostname: "{{ inventory_hostname }}"

- name: Start Benchmark
  hosts: clients
  become: yes
  tasks:
    - name: Start tootbench client
      systemd:
        name: tootbench.service
        state: started
